#!/bin/bash
# Copyright 2015-2016 Jones Magloire (Joxit)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CMD=$1
if [ "$1" = "serve" ]; then
  ARGS="--host 0.0.0.0"
  PORT="-p 6789:6789"
fi

shift

ARGS="$ARGS $@"

docker run -ti --rm $PORT -v $(pwd):/opt/project -e USER_ID=1000 $KOSMTIK_OPTS joxit/kosmtik kosmtik $CMD $ARGS

